// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class IconifyLighter {
  IconifyLighter._();

  /// Used to generate IconData for Ionicons
  /// Go to https://github.com/josephyaduvanshi/flutter_iconify for more information.
  static const _kFontFam = 'IconifyLighter';
  static const String _kFontPkg = "flutter_iconify";

  static const IconData about =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_bookmark =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bebo =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark__1_ =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_all =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connect =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contacts =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cursor =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_bookmark =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_from_the_cloud =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_link =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook__1_ =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female_user =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData for_you =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_cursor =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_file =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram_old =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailbox =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myspace_3 =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_synchronize =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opened_folder =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus__ =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove_bookmark =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restart =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData round =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_3 =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData synchronize =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tick_box =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tinder =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_can =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toolbox =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unavailable =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undelete =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uncheck_all =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_to_the_cloud =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_male =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x2 =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accounting =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accuracy =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ad_blocker =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_graph_report =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_reminder =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agree =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agreement_delete =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agreement_like =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData area_chart =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_resume_female =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_return =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData art_prices =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attitude =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach_resume_male =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audit =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attract_customers =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b2b =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bad_idea =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brainstorm_skill =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brainstorm =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData branding =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brief =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_settings =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData briefcase_1 =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brochure =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_building =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_documentation =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_network =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_program =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collaboration_female_male =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collaboration =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collect =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collectibles =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData combo_chart =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commercial =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commodity =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cover_up =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData craft_work =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_document =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons_by =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creating =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons_commercial =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons_nd =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons_nc =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creativity =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agreement_new =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agreement =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarms =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alcoholic_beverage_licensing =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analyzing_skill =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData answers =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData applicant =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appointment_scheduling =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData approval =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData approve =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData badge =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_safe =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData banner =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barbershop =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blockchain_new_logo =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blockchain =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blog =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bonds =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bounced_check =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData businessman =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData businesswoman =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData butting_in =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cashbook =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cent =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData client_management =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_position =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData communication =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData complaint =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confectionery =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conference =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData conflict =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_details =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyleft =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copyright_all_rights_reserved =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData advance =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_to =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData below =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_down_left__1_ =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_down_left =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_down_right =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_right =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_up_left =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circular_arrows =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collapse_arrow__1_ =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collapse_arrow =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compress =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curly_arrow =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curved_arrow =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_down =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_left =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_right =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_3 =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_up =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_button =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_left_arrow =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_right__1_ =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_right__2_ =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_right =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downward_arrow__1_ =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downward_arrow =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_down =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drag =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enlarge =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_arrow =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_1 =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_arrow =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_button =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go_back =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last_1 =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_2 =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_3 =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_and_right_arrows =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love_arrow =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_down_2 =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_left =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_right =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_down =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_up =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next_page =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_rotate_left =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prev =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_all_arrow =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_arrow =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_vertical =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData return_1 =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_2 =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_button =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_left =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate_right =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rotate =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_down =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_up =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortcut =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slide_up =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_down =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_left =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_right =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_up =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squiggly_arrow =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_turn_to_left =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_turn_to_right =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_turn =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_2 =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_squared =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_down_arrow =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_3 =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upward_arrow =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_control =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData critical_thinking =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData currency_exchange =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_insight =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_insights_manager =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decision_making =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_support =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decision =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decrease =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData demand =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData department =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData development_skill =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_care =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disapprove =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disclaimer =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dividends =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData documents =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_bitcoin_exchange =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donate =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donation =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doughnut_chart =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_resume =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData engage =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enterprise_resource_planning =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equity_security =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData estimates =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData europe_news =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exhibitor =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_influence =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expired =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_food_drive_thru =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial_analytics =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial_changes =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial_dynamic_presentation =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial_growth_analysis =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial_success =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial_tasks =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flip_chart =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flow_chart =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flow =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData franchise =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fund_accounting =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData futures =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gantt_chart =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general_ledger =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grocery_store =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_of_projects =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_task =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growing_money =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guarantee =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_with_pen =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierarchy =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high_priority =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData human_resources =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea_bank =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData idea_1 =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData important_book =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData important_note =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData increase =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information_pyramid =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData innovation =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData input =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inspection =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internet =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internship =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investment =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invite =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job_seeker =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData journal =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knowledge_transfer =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData landlord =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData learn_more =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leave =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lecture =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lecturer =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ledger =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line_chart =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData load_resume_template =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData long_position =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low_priority =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_advertising =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_contact =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData man_with_money =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData management__1_ =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData management =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manager =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maslow_pyramid =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_priority =
      IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meeting_room =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mind_map =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mind =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mission =
      IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_payment =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mockup =
      IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_circulation =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_transfer =
      IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_yours =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multichannel =
      IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name_tag_woman_horizontal =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name_tag_woman =
      IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name_tag =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neutral_decision =
      IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neutral_trading =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_company =
      IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_contact =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_job =
      IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_resume_template =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_slide =
      IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_store =
      IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData news_1 =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_hidden_fee_british_pound =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_hidden_fees =
      IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_idea =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData non_profit_organisation =
      IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData normal_distribution_histogram =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note_taking =
      IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noticeboard =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification =
      IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData office =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData omnichannel__1_ =
      IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData omnichannel =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onboarding =
      IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_money_transfer =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_payment =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_support =
      IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organization_chart_people =
      IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organization =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parallel_workflow =
      IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paycheque =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payroll =
      IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData peak_performers =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_working_together =
      IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData permanent_job =
      IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_growth =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personal_growth =
      IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_contact =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart =
      IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pipeline =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza_delivery =
      IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planner =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portfolio =
      IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData post_ads =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presentation =
      IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy_policy =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy =
      IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proactivity =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process_improvement =
      IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product_documents =
      IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profit_analysis =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profit_presentation =
      IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profit =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project_setup__1_ =
      IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project_setup =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData project =
      IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prototype =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData punctuality =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purposeful_man =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purposeful_woman =
      IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionnaire =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questions =
      IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ratings =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recurring_appointment_exception =
      IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData registered_trademark =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData related_companies =
      IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rent__1_ =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rent =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_money =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData request_service =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData requirement =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rescheduling_a_task =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reseller =
      IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reset =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resume =
      IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room_finder =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rubber_stamp =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rules_book =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rules =
      IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary_female =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary_male =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sales_performance =
      IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sankey =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satisfaction =
      IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scatter_plot =
      IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule =
      IconData(0xe9c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school =
      IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_client =
      IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_pass =
      IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sepa =
      IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service =
      IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_mall =
      IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short_position =
      IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shortlist =
      IconData(0xe9cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signature =
      IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signing_a_document =
      IconData(0xe9cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_business =
      IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sorting =
      IconData(0xe9d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker_notes_off =
      IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker_notes =
      IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData split_money =
      IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprint_iteration =
      IconData(0xe9d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stacked_organizational_chart_highlighted_first_node =
      IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stacked_organizational_chart =
      IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stamp =
      IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics_report =
      IconData(0xe9d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics =
      IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock_share =
      IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stocks =
      IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe =
      IconData(0xe9dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData submit_resume =
      IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData summary_list =
      IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supplier =
      IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData survey =
      IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target =
      IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_completed =
      IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_planning =
      IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task =
      IconData(0xe9e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasklist =
      IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks =
      IconData(0xe9e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tax =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teamwork =
      IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technical_support =
      IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_card =
      IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_management =
      IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline =
      IconData(0xe9ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tips =
      IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_do =
      IconData(0xe9ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData todo_list =
      IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction_list =
      IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel_agency =
      IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_structure =
      IconData(0xe9f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trust =
      IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_shaped_style =
      IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unit =
      IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_link_document =
      IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vastu_consultancy =
      IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_timeline =
      IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_conference =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_projector =
      IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vip =
      IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa_stamp =
      IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warranty =
      IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weak_financial_growth =
      IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web_advertising =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web_analytics =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData what_i_do =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wish_list =
      IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdrawal =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work =
      IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workflow =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yard_sale =
      IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData EighteenPlus =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bit_32 =
      IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bit_64 =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aac =
      IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_1 =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_dollar =
      IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_link =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_phone =
      IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book_2 =
      IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_book_1 =
      IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airport =
      IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify =
      IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData american_express =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_l_battery =
      IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apk =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_watch =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apply =
      IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asia =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at_sign =
      IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ask_question =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach =
      IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auction =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio_file =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData automation =
      IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bakery =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_building =
      IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_card_dollar__1_ =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_card_dollar =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_cards__1_ =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bank_cards =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData batman =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData batteries =
      IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_alert =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_level =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData billing_machine =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binary_file =
      IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData binoculars =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bios =
      IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin_accepted =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_microphone =
      IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_connected =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth =
      IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_2 =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bonds_1 =
      IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blur =
      IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bot =
      IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_phone =
      IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData browse_podcasts =
      IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buffet_breakfast =
      IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullet_list =
      IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_drive_2 =
      IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe_building =
      IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_drive =
      IconData(0xea41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe =
      IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_disconnected =
      IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_forwarding =
      IconData(0xea45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call_list =
      IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call =
      IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_subscription =
      IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_exchange =
      IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_security =
      IconData(0xea4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cellular_network =
      IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkout =
      IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheque =
      IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble =
      IconData(0xea4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData charging_battery =
      IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle =
      IconData(0xea51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_play =
      IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circled_thin =
      IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard =
      IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_backup_restore =
      IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_print =
      IconData(0xea56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xea57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code =
      IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments_1 =
      IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData commercial_1 =
      IconData(0xea5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData company_1 =
      IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass =
      IconData(0xea5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confirm =
      IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connected =
      IconData(0xea5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer_mouse =
      IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData console =
      IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy =
      IconData(0xea62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData country =
      IconData(0xea63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create_archive =
      IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData create =
      IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      IconData(0xea66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cv =
      IconData(0xea67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_center =
      IconData(0xea68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_transfer =
      IconData(0xea69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database_view =
      IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database =
      IconData(0xea6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData defense =
      IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_link =
      IconData(0xea6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_message =
      IconData(0xea6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_shield =
      IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_ticket =
      IconData(0xea70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData developer_mode =
      IconData(0xea71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData device_information =
      IconData(0xea72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dialing_number =
      IconData(0xea73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond =
      IconData(0xea74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dining =
      IconData(0xea75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dividends_1 =
      IconData(0xea76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dns =
      IconData(0xea77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData do_not_disturb_ios =
      IconData(0xea78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dvd_logo =
      IconData(0xea79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dvi =
      IconData(0xea7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earbud_headphones =
      IconData(0xea7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth_globe =
      IconData(0xea7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_file =
      IconData(0xea7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education =
      IconData(0xea7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eight_plus =
      IconData(0xea7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject =
      IconData(0xea80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric_bike =
      IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData end_call =
      IconData(0xea82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope =
      IconData(0xea83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error =
      IconData(0xea84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethernet_off =
      IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_csv =
      IconData(0xea86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_pdf =
      IconData(0xea87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export =
      IconData(0xea88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xea89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id =
      IconData(0xea8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fail =
      IconData(0xea8b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward_round =
      IconData(0xea8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first =
      IconData(0xea8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fit_to_page =
      IconData(0xea8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness =
      IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fm_radio =
      IconData(0xea90, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food_bar =
      IconData(0xea91, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gas_station =
      IconData(0xea92, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear =
      IconData(0xea93, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_card =
      IconData(0xea94, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xea95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData giving_tickets =
      IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gmail_login =
      IconData(0xea97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData good_quality =
      IconData(0xea98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduate =
      IconData(0xea99, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_scroll =
      IconData(0xea9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym =
      IconData(0xea9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy =
      IconData(0xea9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdd =
      IconData(0xea9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hdmi_cable =
      IconData(0xea9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset =
      IconData(0xea9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_data =
      IconData(0xeaa0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help =
      IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high_importance =
      IconData(0xeaa2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xeaa3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_sign =
      IconData(0xeaa4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital =
      IconData(0xeaa5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hot_line =
      IconData(0xeaa6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotline =
      IconData(0xeaa7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imdb =
      IconData(0xeaa8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import_pdf =
      IconData(0xeaa9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData import =
      IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData incoming_call =
      IconData(0xeaab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData index =
      IconData(0xeaac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData input_component =
      IconData(0xeaad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inspect_code =
      IconData(0xeaae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData installing_updates =
      IconData(0xeaaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internet_1 =
      IconData(0xeab0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData investment_1 =
      IconData(0xeab1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ios_logo =
      IconData(0xeab2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iphone_x =
      IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ipv6 =
      IconData(0xeab4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData json =
      IconData(0xeab5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kite_shape =
      IconData(0xeab6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_alert =
      IconData(0xeab7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_coding =
      IconData(0xeab8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_error__1_ =
      IconData(0xeab9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_error =
      IconData(0xeaba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop_play_video =
      IconData(0xeabb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laptop =
      IconData(0xeabc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last_24_hours =
      IconData(0xeabd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData last =
      IconData(0xeabe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xeabf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData literature =
      IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location__1_ =
      IconData(0xeac1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xeac2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 =
      IconData(0xeac3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low_connection =
      IconData(0xeac4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low_importance =
      IconData(0xeac5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low_volume =
      IconData(0xeac6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail =
      IconData(0xeac7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map =
      IconData(0xeac8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mastercard =
      IconData(0xeac9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meal =
      IconData(0xeaca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal =
      IconData(0xeacb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memory_slot =
      IconData(0xeacc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_squared =
      IconData(0xeacd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_1 =
      IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messaging =
      IconData(0xeacf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData micro_sd =
      IconData(0xead0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microchip =
      IconData(0xead1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData missed_call =
      IconData(0xead2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_box =
      IconData(0xead3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money =
      IconData(0xead4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motherboard =
      IconData(0xead5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_left_1 =
      IconData(0xead6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie_ticket =
      IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mp3 =
      IconData(0xead8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multiple_devices =
      IconData(0xead9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_library =
      IconData(0xeada, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_1 =
      IconData(0xeadb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_location =
      IconData(0xeadc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigate =
      IconData(0xeadd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData network_drive =
      IconData(0xeade, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData networking_manager =
      IconData(0xeadf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_letter =
      IconData(0xeae0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_ticket =
      IconData(0xeae1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next =
      IconData(0xeae2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc =
      IconData(0xeae3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_audio =
      IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_connection =
      IconData(0xeae5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_reminders =
      IconData(0xeae6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_sim_card =
      IconData(0xeae7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_smoking =
      IconData(0xeae8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_video =
      IconData(0xeae9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nokia_3310 =
      IconData(0xeaea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData north_direction =
      IconData(0xeaeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_center =
      IconData(0xeaec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offline =
      IconData(0xeaed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online =
      IconData(0xeaee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData operating_system =
      IconData(0xeaef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_history =
      IconData(0xeaf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paid_bill_stamp =
      IconData(0xeaf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper =
      IconData(0xeaf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pass_fail =
      IconData(0xeaf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pass =
      IconData(0xeaf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_key =
      IconData(0xeaf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_squared =
      IconData(0xeaf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_history =
      IconData(0xeaf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal =
      IconData(0xeaf8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_drive =
      IconData(0xeaf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData performance_macbook =
      IconData(0xeafa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_case =
      IconData(0xeafb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_in_circle =
      IconData(0xeafc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xeafd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData place_marker =
      IconData(0xeafe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xeaff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData playlist =
      IconData(0xeb00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData postcode =
      IconData(0xeb01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_off_button =
      IconData(0xeb02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_over_ethernet =
      IconData(0xeb03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData previous =
      IconData(0xeb04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print =
      IconData(0xeb05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData program =
      IconData(0xeb06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData programming =
      IconData(0xeb07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protect =
      IconData(0xeb08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData public_safety =
      IconData(0xeb09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchase_order =
      IconData(0xeb0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData push_notifications =
      IconData(0xeb0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote =
      IconData(0xeb0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_2 =
      IconData(0xeb0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radio_waves =
      IconData(0xeb0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rating_off =
      IconData(0xeb0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rating =
      IconData(0xeb10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rca =
      IconData(0xeb11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reading =
      IconData(0xeb12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recharge_battery =
      IconData(0xeb13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo_1 =
      IconData(0xeb14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData region =
      IconData(0xeb15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remote_desktop =
      IconData(0xeb16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_one =
      IconData(0xeb17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat =
      IconData(0xeb18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rest_api =
      IconData(0xeb19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restaurant =
      IconData(0xeb1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rewind_button_round =
      IconData(0xeb1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ring =
      IconData(0xeb1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ringer_volume =
      IconData(0xeb1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ringing_phone =
      IconData(0xeb1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rounded_square =
      IconData(0xeb1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rs_232_female =
      IconData(0xeb20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rs_232_male =
      IconData(0xeb21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sale =
      IconData(0xeb22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellite =
      IconData(0xeb23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData satellites =
      IconData(0xeb24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xeb25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sd =
      IconData(0xeb26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData secure_mail =
      IconData(0xeb27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData secured_letter =
      IconData(0xeb28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_wi_fi =
      IconData(0xeb29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_letter =
      IconData(0xeb2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xeb2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sent =
      IconData(0xeb2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shake_phone =
      IconData(0xeb2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xeb2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short_film =
      IconData(0xeb2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle =
      IconData(0xeb30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shutdown =
      IconData(0xeb31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      IconData(0xeb32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sim_card =
      IconData(0xeb33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_15_seconds_back =
      IconData(0xeb34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_ahead_15_seconds =
      IconData(0xeb35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone_approve =
      IconData(0xeb36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smartphone_ram =
      IconData(0xeb37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smoker =
      IconData(0xeb38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smoking =
      IconData(0xeb39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sms =
      IconData(0xeb3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sniper =
      IconData(0xeb3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound_cloud =
      IconData(0xeb3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData south_direction =
      IconData(0xeb3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spyware =
      IconData(0xeb3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ssd =
      IconData(0xeb3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack__1_ =
      IconData(0xeb40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack =
      IconData(0xeb41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xeb42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData start =
      IconData(0xeb43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stock_share_1 =
      IconData(0xeb44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_circled =
      IconData(0xeb45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_squared =
      IconData(0xeb46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xeb47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData street_view =
      IconData(0xeb48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData submit_document =
      IconData(0xeb49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_shirt =
      IconData(0xeb4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_of_content =
      IconData(0xeb4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test_passed =
      IconData(0xeb4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theatre_mask =
      IconData(0xeb4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thin_client =
      IconData(0xeb4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbnails =
      IconData(0xeb4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunderbolt =
      IconData(0xeb50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket =
      IconData(0xeb51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle_off =
      IconData(0xeb52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top_menu =
      IconData(0xeb53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData topup_payment =
      IconData(0xeb54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torrent =
      IconData(0xeb55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData touchpad =
      IconData(0xeb56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv_14 =
      IconData(0xeb57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv_g =
      IconData(0xeb58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv_ma =
      IconData(0xeb59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tv_pg =
      IconData(0xeb5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_tickets =
      IconData(0xeb5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData typing =
      IconData(0xeb5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unavailable_cloud =
      IconData(0xeb5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo_1 =
      IconData(0xeb5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uninstalling_updates =
      IconData(0xeb5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlike =
      IconData(0xeb60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock =
      IconData(0xeb61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpin_2 =
      IconData(0xeb62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpin =
      IconData(0xeb63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unread_messages =
      IconData(0xeb64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsubscribe =
      IconData(0xeb65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_mail =
      IconData(0xeb66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_to_cloud =
      IconData(0xeb67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usb_connected =
      IconData(0xeb68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usb_memory_stick =
      IconData(0xeb69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData versions =
      IconData(0xeb6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_call =
      IconData(0xeb6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_message =
      IconData(0xeb6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_headline =
      IconData(0xeb6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_more =
      IconData(0xeb6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa =
      IconData(0xeb6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voice =
      IconData(0xeb70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voicemail =
      IconData(0xeb71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voip =
      IconData(0xeb72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voltmeter =
      IconData(0xeb73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vpn_status_bar_icon =
      IconData(0xeb74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vpn =
      IconData(0xeb75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet =
      IconData(0xeb76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warranty_1 =
      IconData(0xeb77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water =
      IconData(0xeb78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web_address =
      IconData(0xeb79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web_analytics_1 =
      IconData(0xeb7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData website =
      IconData(0xeb7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData where =
      IconData(0xeb7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi_connected =
      IconData(0xeb7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi_disconnected =
      IconData(0xeb7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi_lock =
      IconData(0xeb7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi_off =
      IconData(0xeb80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wi_fi =
      IconData(0xeb81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine_bar =
      IconData(0xeb82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData without_internet =
      IconData(0xeb83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world_map =
      IconData(0xeb84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zip_code =
      IconData(0xeb85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zip =
      IconData(0xeb86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in =
      IconData(0xeb87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out =
      IconData(0xeb88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
